USE [master]
GO

/****** Object:  Database [Standard]    Script Date: 26/05/2022 14:59:04 ******/
CREATE DATABASE [Standard]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Standard', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\Standard.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Standard_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\Standard_log.ldf' , SIZE = 73728KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [Standard] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Standard].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Standard] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Standard] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Standard] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Standard] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Standard] SET ARITHABORT OFF 
GO

ALTER DATABASE [Standard] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Standard] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Standard] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Standard] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Standard] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Standard] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Standard] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Standard] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Standard] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Standard] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Standard] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Standard] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Standard] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Standard] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Standard] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Standard] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Standard] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Standard] SET RECOVERY FULL 
GO

ALTER DATABASE [Standard] SET  MULTI_USER 
GO

ALTER DATABASE [Standard] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Standard] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Standard] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Standard] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Standard] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Standard] SET QUERY_STORE = OFF
GO

USE [Standard]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [Standard] SET  READ_WRITE 
GO

