//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaticData
    {
        public int MinStudentInTeaching { get; set; }
        public int MaxStudentInTeaching { get; set; }
        public int minStudentInTichunim { get; set; }
        public int maxStudentInTichunim { get; set; }
        public double maxPositionHours { get; set; }
        public Nullable<System.DateTime> BeginingOfYear { get; set; }
        public Nullable<double> EngagedStandard { get; set; }
        public System.DateTime UpdateDate { get; set; }
    }
}
