//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Teacher()
        {
            this.TeachingAvailabilities = new HashSet<TeachingAvailability>();
        }
    
        public int TeachingId { get; set; }
        public int TeacherId { get; set; }
        public Nullable<int> TeachingGrade { get; set; }
        public string TeacherFirstName { get; set; }
        public string TeacherLastName { get; set; }
        public string TeacherTz { get; set; }
        public bool IsActive { get; set; }
        public string PhoneNumber { get; set; }
        public string Adress { get; set; }
        public string Email { get; set; }
        public double PositionHours { get; set; }
        public Nullable<int> Permission { get; set; }
        public Nullable<int> TeacherGroup { get; set; }
        public Nullable<double> TeacherStandard { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeachingAvailability> TeachingAvailabilities { get; set; }
    }
}
